wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/cleanrl_dqn_atari.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.19
    start_time: 1716980055.358377
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.19
      5: 0.13.11
      8:
      - 5
batch_size:
  desc: null
  value: 32
buffer_size:
  desc: null
  value: 100000
capture_video:
  desc: null
  value: true
cuda:
  desc: null
  value: true
cuda_num:
  desc: null
  value: 0
end_e:
  desc: null
  value: 0.01
env_id:
  desc: null
  value: ALE/Breakout-v5
exp_name:
  desc: null
  value: cleanrl_dqn_atari
exploration_fraction:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.99
hf_entity:
  desc: null
  value: ''
learning_rate:
  desc: null
  value: 0.0001
learning_starts:
  desc: null
  value: 80000
num_envs:
  desc: null
  value: 1
save_model:
  desc: null
  value: true
seed:
  desc: null
  value: 1
start_e:
  desc: null
  value: 1
target_network_frequency:
  desc: null
  value: 1000
tau:
  desc: null
  value: 1.0
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 1000000
track:
  desc: null
  value: true
train_frequency:
  desc: null
  value: 4
upload_model:
  desc: null
  value: false
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: rl_hw4_atari
